# Generated by Django 4.2.7 on 2025-12-16 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(help_text="The question text")),
                ("answer", models.TextField(help_text="The answer text")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("borrowing", "Borrowing & Reservations"),
                            ("inventory", "Inventory & Items"),
                            ("hubs", "Hubs & Locations"),
                            ("mentorship", "Mentorship"),
                            ("community", "Community & Badges"),
                            ("account", "Account & Profile"),
                            ("technical", "Technical Support"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords for search optimization"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of times viewed"),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, help_text="Number of helpful votes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ Entry",
                "verbose_name_plural": "FAQ Entries",
                "db_table": "ori_ai_faq",
                "ordering": ["-helpful_count", "-view_count"],
            },
        ),
    ]
