# Generated by Django 4.2.7 on 2025-12-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("quantity_total", models.IntegerField(default=1)),
                ("quantity_available", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("damaged", "Damaged"),
                            ("reserved", "Reserved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donated_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="hubs.hub",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="inventory_i_categor_72dfbb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="inventory_i_status_dd76b8_idx"
                    ),
                    models.Index(
                        fields=["hub", "status"], name="inventory_i_hub_id_662cc6_idx"
                    ),
                ],
            },
        ),
    ]
