# Generated by Django 4.2.7 on 2025-12-17 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_user_managers"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="level",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("newcomer", "Newcomer"),
                            ("nesting", "Nesting"),
                            ("grounded", "Grounded"),
                            ("trusted_wing", "Trusted Wing"),
                            ("flock_anchor", "Flock Anchor"),
                        ],
                        default="newcomer",
                        max_length=20,
                    ),
                ),
                ("total_contributions", models.IntegerField(default=0)),
                ("total_reservations", models.IntegerField(default=0)),
                ("total_connections", models.IntegerField(default=0)),
                ("last_level_change", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_levels",
            },
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["category", "sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="badge",
            name="color",
            field=models.CharField(default="#3B82F6", max_length=7),
        ),
        migrations.AddField(
            model_name="badge",
            name="icon",
            field=models.CharField(default="🏆", max_length=50),
        ),
        migrations.AddField(
            model_name="badge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="badge",
            name="unlocks_feature",
            field=models.CharField(
                blank=True,
                help_text="Optional feature this badge unlocks",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="awarded_reason",
            field=models.TextField(blank=True, help_text="Optional Ori message"),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="category",
            field=models.CharField(
                choices=[
                    ("arrival", "Arrival & Belonging"),
                    ("contribution", "Contribution & Care"),
                    ("community", "Community Energy"),
                    ("trust", "Steward & Trust"),
                    ("milestone", "Milestone"),
                    ("mentorship", "Mentorship"),
                ],
                max_length=20,
            ),
        ),
    ]
