# Generated by Django 4.2.7 on 2025-12-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("hubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_users",
                to="hubs.hub",
            ),
        ),
    ]
