# Generated by Django 4.2.7 on 2025-12-16 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_assigned_hub"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
