# Generated by Django 4.2.7 on 2025-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short introduction (max 500 chars)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="languages_spoken",
            field=models.JSONField(
                blank=True, default=list, help_text="Languages the user speaks"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text="Skills user can teach or share"
            ),
        ),
    ]
