# Generated by Django 4.2.7 on 2025-12-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_bio_user_languages_spoken_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
