# Generated by Django 4.2.7 on 2025-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_choice",
            field=models.CharField(
                blank=True,
                help_text="Selected avatar from predefined options (e.g., avatar1, avatar2)",
                max_length=50,
                null=True,
            ),
        ),
    ]
